# Generated by Django 2.2 on 2020-08-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numner',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='categoty',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
