# Generated by Django 2.2 on 2020-08-18 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='intoduce_yourself',
            new_name='introduce_yourself',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='intoduce_yourself',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[users.validators.validate_phone_number], verbose_name='شماره اضطراری'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('تولید کننده', 'تولید کننده'), ('پخش کننده', 'پخش کننده'), ('وارد کننده', 'وارد کننده'), ('خدمات', 'خدمات'), ('عمده فروش', 'عمده فروش'), ('بنک دار', 'بنک دار'), ('دولتی', 'دولتی'), ('متفرقه', 'متفرقه')], max_length=20, null=True, verbose_name='زمینه کاری'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='دپارتمان'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.validate_phone_number], verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='عنوان شغلی'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[users.validators.validate_phone_number], verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_phone_num',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.validate_phone_number], verbose_name='شماره تلفن دفتر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_numner',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='web_site',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='آدرس وبسایت'),
        ),
    ]
