# Generated by Django 2.2 on 2020-08-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CustomeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='نام')),
                ('value', models.CharField(blank=True, max_length=32, null=True, verbose_name='مقدار')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('resistance', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundPerMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StandardProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='نام')),
                ('value', models.CharField(blank=True, max_length=32, null=True, verbose_name='مقدار')),
                ('is_active', models.BooleanField(default=True)),
                ('it_has', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='نام دسته بندی')),
                ('description', models.TextField(blank=True, null=True)),
                ('boxing', models.ManyToManyField(blank=True, null=True, to='categories.Boxing')),
                ('custome_property', models.ManyToManyField(blank=True, null=True, to='categories.CustomeProperty')),
                ('material', models.ManyToManyField(blank=True, null=True, to='categories.Material')),
                ('round_per_minute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.RoundPerMinute')),
                ('size', models.ManyToManyField(blank=True, null=True, to='categories.Size')),
                ('standar_properties', models.ManyToManyField(blank=True, null=True, to='categories.StandardProperty')),
                ('sub_category_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
