# Generated by Django 2.2 on 2020-08-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=132, verbose_name='نام محصول')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='قیمت محصول')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='قیمت تخفیف')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
                ('stock', models.IntegerField(default=1, verbose_name='موجودی')),
                ('description', models.TextField()),
                ('minimum_order', models.CharField(blank=True, max_length=32, null=True, verbose_name='حداقل تعداد جهت سفارش')),
                ('payment_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='روش پرداخت')),
                ('packing', models.CharField(blank=True, max_length=32, null=True, verbose_name='بسته بندی')),
                ('shipping', models.CharField(blank=True, max_length=32, null=True, verbose_name='نحوه ارسال')),
                ('origin', models.CharField(blank=True, max_length=32, null=True, verbose_name='اصالت کالا')),
                ('made_in', models.CharField(blank=True, max_length=32, null=True, verbose_name='تولید کشور')),
                ('delivery', models.CharField(blank=True, max_length=32, null=True, verbose_name='بازه زمانی ارسال')),
                ('samples', models.CharField(blank=True, choices=[('خیر', 'خیر'), ('رایگان', 'رایگان'), ('اعمال هزینه', 'اعمال هزینه')], max_length=24, null=True, verbose_name='ارائه نمونه')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('category', models.ManyToManyField(to='categories.Category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProducerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attachment', models.ImageField(blank=True, upload_to='')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variation')),
            ],
            options={
                'unique_together': {('variation', 'value')},
            },
        ),
    ]
